/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 88e58fb6934b22473b1d82ab906169a4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		OPENAI_API_KEY: string;
		OPENAI_GATEWAY_URL: string;
		// Optional providers for multi-model rotation
		ANTHROPIC_API_KEY?: string;
		ANTHROPIC_GATEWAY_URL?: string;
		GOOGLE_API_KEY?: string;
		GOOGLE_GATEWAY_URL?: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "OPENAI_GATEWAY_URL">> {}
}
